### ISSUE TITLE
Predicted species distribution shifted?

### ISSUE THREAD

**Issue by KendraStraub** [nationalparkservice/npmap-species#71]
![3](https://cloud.githubusercontent.com/assets/8036575/10230324/77fe6d82-684a-11e5-9dc8-a1b585228eab.PNG)

Seems as though the distribution is shifted in the SW corner of the park. See photo. 

Commenter: Keith Langdon, former GRSM I&M program coordinator

"The predicted data appears to be mis-registered.  When you take a ubiquitous species like say Acer rubrum, and then check  at close resolution along the northern and southern park boundary, it appears that the predictive (color) data is mis-registered 100-300m to the SW. Check it out. "

**Comment by tpcolson** [comment]
When compared to the environmental layers, it appears that the registration shift is occurring when the clipping to the park boundary is performed. This error is present in the Maxent output asc file and being carried forward into the mapbox tiles. 

![image](https://cloud.githubusercontent.com/assets/5861784/10481675/4c5a8fe4-7240-11e5-9f7f-12731557deee.png)

![image](https://cloud.githubusercontent.com/assets/5861784/10481698/7197cda8-7240-11e5-941f-4789ea2b1ec4.png)


![image](https://cloud.githubusercontent.com/assets/5861784/10481727/9fd6efaa-7240-11e5-8003-9fcb981561f4.png)

**Comment by tpcolson** [comment]
This has been resolved.

**Comment by KendraStraub** [comment]
@tpcolson  and @jduggan1 
I still see the shift. 
![image](https://cloud.githubusercontent.com/assets/8036575/16955626/5be32ed2-4da3-11e6-8b39-7924146132f5.png)
